name: Node CI/CD

on:
  push:
    branches: [ main ]
  pull_request:

env:
  NODE_VERSION: '14'

jobs:

  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VERSION }}
      
      - name: Install dependencies
        run: npm install
      
      - name: Test
        run: npm test

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VERSION }}
      
      - name: Lint code
        run: npm lint

  docker-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          registry: 'docker.io'
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Build Docker image
        id: build
        run: docker build -t node-app .

      - name: Push Docker image to Docker Hub
        uses: docker/push-action@v2
        with:
          image: node-app

  deploy-to-k8s:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Kubernetes cluster (replace with your setup)
        run: kubectl apply -f deployment.yaml
      
      - name: Deploy application using Kubernetes
        run: kubectl create deployment node-app --image=docker.io/yourusername/node-app